package money.plan;

public enum PlanOrderByFields {
	PLANID, PLANID_DESC, PLANDATE, PLANDATE_DESC, STARTDATE, STARTDATE_DESC, ENDDATE, ENDDATE_DESC, REALSTARTDATE, REALSTARTDATE_DESC, REALENDDATE, REALENDDATE_DESC, PLANDESC, PLANDESC_DESC, PLANTYPE, PLANTYPE_DESC, PLANSTATUS, PLANSTATUS_DESC, USERID, USERID_DESC
}
