
package ido.LoginUser;

/**
 * 关于系统用户的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum LoginUserSearchFields { 
 SNO , USERNAME , USERID , USERTYPE , USERUNIT , USERPASS , USERSTATUS , USERPHONE , USEREMAIL , USERADDRESS , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,USERNAME_COM_EQUALS,USERNAME_COM_NOT_EQUALS
,USERID_COM_EQUALS,USERID_COM_NOT_EQUALS
,USERTYPE_COM_EQUALS,USERTYPE_COM_NOT_EQUALS
,USERUNIT_COM_EQUALS,USERUNIT_COM_NOT_EQUALS
,USERPASS_COM_EQUALS,USERPASS_COM_NOT_EQUALS
,USERSTATUS_COM_EQUALS,USERSTATUS_COM_NOT_EQUALS
,USERPHONE_COM_EQUALS,USERPHONE_COM_NOT_EQUALS
,USEREMAIL_COM_EQUALS,USEREMAIL_COM_NOT_EQUALS
,USERADDRESS_COM_EQUALS,USERADDRESS_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
