
package ido.LoginUser;

/**
 * 关于系统用户的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum LoginUserOrderByFields { 
 SNO,  SNO_DESC , USERNAME,  USERNAME_DESC , USERID,  USERID_DESC , USERTYPE,  USERTYPE_DESC , USERUNIT,  USERUNIT_DESC , USERPASS,  USERPASS_DESC , USERSTATUS,  USERSTATUS_DESC , USERPHONE,  USERPHONE_DESC , USEREMAIL,  USEREMAIL_DESC , USERADDRESS,  USERADDRESS_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
