
package ido.BusinessGroup;

/**
 * 关于商家集团的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum BusinessGroupOrderByFields { 
 SNO,  SNO_DESC , GROUPSNO,  GROUPSNO_DESC , GROUPNAME,  GROUPNAME_DESC , GROUPEMAIL,  GROUPEMAIL_DESC , GROUPCONTACT,  GROUPCONTACT_DESC , GROUPCONTACTPHONE,  GROUPCONTACTPHONE_DESC , GROUPCONTACTMOBILE,  GROUPCONTACTMOBILE_DESC , GROUPSTATUS,  GROUPSTATUS_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
