
package ido.BusinessGroup;

/**
 * 关于商家集团的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum BusinessGroupSearchFields { 
 SNO , GROUPSNO , GROUPNAME , GROUPEMAIL , GROUPCONTACT , GROUPCONTACTPHONE , GROUPCONTACTMOBILE , GROUPSTATUS , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,GROUPSNO_STR_EQUALS,GROUPSNO_STR_LIKE,GROUPSNO_STR_NOT_LIKE,GROUPSNO_STR_NOT_EQUALS
,GROUPNAME_STR_EQUALS,GROUPNAME_STR_LIKE,GROUPNAME_STR_NOT_LIKE,GROUPNAME_STR_NOT_EQUALS
,GROUPEMAIL_STR_EQUALS,GROUPEMAIL_STR_LIKE,GROUPEMAIL_STR_NOT_LIKE,GROUPEMAIL_STR_NOT_EQUALS
,GROUPCONTACT_STR_EQUALS,GROUPCONTACT_STR_LIKE,GROUPCONTACT_STR_NOT_LIKE,GROUPCONTACT_STR_NOT_EQUALS
,GROUPCONTACTPHONE_STR_EQUALS,GROUPCONTACTPHONE_STR_LIKE,GROUPCONTACTPHONE_STR_NOT_LIKE,GROUPCONTACTPHONE_STR_NOT_EQUALS
,GROUPCONTACTMOBILE_STR_EQUALS,GROUPCONTACTMOBILE_STR_LIKE,GROUPCONTACTMOBILE_STR_NOT_LIKE,GROUPCONTACTMOBILE_STR_NOT_EQUALS
,GROUPSTATUS_COM_EQUALS,GROUPSTATUS_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
