
package money.bugList;

/**
 * 关于问题清单的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum BugListSearchFields { 
 SNO , BUGTYPE , BUGDESC , CREATEUSER , CREATETIME , NEEDTIME , CONSOLEPEOPLE , CONSOLETILE , REMARK ,BUGTYPE_COM_EQUALS,BUGTYPE_COM_NOT_EQUALS
,BUGDESC_COM_EQUALS,BUGDESC_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,NEEDTIME_COM_EQUALS,NEEDTIME_COM_NOT_EQUALS
,CONSOLEPEOPLE_COM_EQUALS,CONSOLEPEOPLE_COM_NOT_EQUALS
,CONSOLETILE_COM_EQUALS,CONSOLETILE_COM_NOT_EQUALS
,REMARK_COM_EQUALS,REMARK_COM_NOT_EQUALS
}
