
package money.uploadFile;

/**
 * 关于上传文件的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum UploadFileSearchFields { 
 SNO , BUSINESSID , FILETYPE , ISEXIST , FILENAME , REALFILENAME , FILESIZE , CREATEUSER , CREATETIME ,BUSINESSID_COM_EQUALS,BUSINESSID_COM_NOT_EQUALS
,FILETYPE_COM_EQUALS,FILETYPE_COM_NOT_EQUALS
,ISEXIST_COM_EQUALS,ISEXIST_COM_NOT_EQUALS
,FILENAME_COM_EQUALS,FILENAME_COM_NOT_EQUALS
,REALFILENAME_COM_EQUALS,REALFILENAME_COM_NOT_EQUALS
,FILESIZE_COM_EQUALS,FILESIZE_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
}
