
package ido.BusinessShop;

/**
 * 关于商铺的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum BusinessShopOrderByFields { 
 SNO,  SNO_DESC , SHOPMID,  SHOPMID_DESC , SHOPNAME,  SHOPNAME_DESC , SHOPSNO,  SHOPSNO_DESC , SHOPSTATUS,  SHOPSTATUS_DESC , SHOPCONTACTNAME,  SHOPCONTACTNAME_DESC , SHOPCONPHONE,  SHOPCONPHONE_DESC , SHOPEMAIL,  SHOPEMAIL_DESC , SHOPADDRESS,  SHOPADDRESS_DESC , SHOPDATE,  SHOPDATE_DESC , SHOPJINGDU,  SHOPJINGDU_DESC , SHOPWEIDU,  SHOPWEIDU_DESC , SHOPPROVINCE,  SHOPPROVINCE_DESC , SHOPCITY,  SHOPCITY_DESC , SHOPXIAN,  SHOPXIAN_DESC , SHOPREMARK,  SHOPREMARK_DESC , SHOPMAIN,  SHOPMAIN_DESC , SHOPINTRODUCE,  SHOPINTRODUCE_DESC , SHOPSPECIAL,  SHOPSPECIAL_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
