
package ido.BusinessShop;

/**
 * 关于商铺的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum BusinessShopSearchFields { 
 SNO , SHOPMID , SHOPNAME , SHOPSNO , SHOPSTATUS , SHOPCONTACTNAME , SHOPCONPHONE , SHOPEMAIL , SHOPADDRESS , SHOPDATE , SHOPJINGDU , SHOPWEIDU , SHOPPROVINCE , SHOPCITY , SHOPXIAN , SHOPREMARK , SHOPMAIN , SHOPINTRODUCE , SHOPSPECIAL , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,SHOPMID_COM_EQUALS,SHOPMID_COM_NOT_EQUALS
,SHOPNAME_COM_EQUALS,SHOPNAME_COM_NOT_EQUALS
,SHOPSNO_COM_EQUALS,SHOPSNO_COM_NOT_EQUALS
,SHOPSTATUS_COM_EQUALS,SHOPSTATUS_COM_NOT_EQUALS
,SHOPCONTACTNAME_COM_EQUALS,SHOPCONTACTNAME_COM_NOT_EQUALS
,SHOPCONPHONE_COM_EQUALS,SHOPCONPHONE_COM_NOT_EQUALS
,SHOPEMAIL_COM_EQUALS,SHOPEMAIL_COM_NOT_EQUALS
,SHOPADDRESS_COM_EQUALS,SHOPADDRESS_COM_NOT_EQUALS
,SHOPDATE_COM_EQUALS,SHOPDATE_COM_NOT_EQUALS
,SHOPJINGDU_COM_EQUALS,SHOPJINGDU_COM_NOT_EQUALS
,SHOPWEIDU_COM_EQUALS,SHOPWEIDU_COM_NOT_EQUALS
,SHOPPROVINCE_COM_EQUALS,SHOPPROVINCE_COM_NOT_EQUALS
,SHOPCITY_COM_EQUALS,SHOPCITY_COM_NOT_EQUALS
,SHOPXIAN_COM_EQUALS,SHOPXIAN_COM_NOT_EQUALS
,SHOPREMARK_COM_EQUALS,SHOPREMARK_COM_NOT_EQUALS
,SHOPMAIN_COM_EQUALS,SHOPMAIN_COM_NOT_EQUALS
,SHOPINTRODUCE_COM_EQUALS,SHOPINTRODUCE_COM_NOT_EQUALS
,SHOPSPECIAL_COM_EQUALS,SHOPSPECIAL_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
