
package ido.ConsumeInfo;

/**
 * 关于消费记录的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum ConsumeInfoSearchFields { 
 SNO , IUSERID , COMID , SHOPMID , SHOPID , OWNERCOM , CONSUMESTATUS , CONSUMEMONEY , CARDMONEY , CASHMONEY , CONSUMETIME , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,IUSERID_COM_EQUALS,IUSERID_COM_NOT_EQUALS
,COMID_COM_EQUALS,COMID_COM_NOT_EQUALS
,SHOPMID_COM_EQUALS,SHOPMID_COM_NOT_EQUALS
,SHOPID_COM_EQUALS,SHOPID_COM_NOT_EQUALS
,OWNERCOM_COM_EQUALS,OWNERCOM_COM_NOT_EQUALS
,CONSUMESTATUS_COM_EQUALS,CONSUMESTATUS_COM_NOT_EQUALS
,CONSUMEMONEY_COM_EQUALS,CONSUMEMONEY_COM_NOT_EQUALS
,CARDMONEY_COM_EQUALS,CARDMONEY_COM_NOT_EQUALS
,CASHMONEY_COM_EQUALS,CASHMONEY_COM_NOT_EQUALS
,CONSUMETIME_COM_EQUALS,CONSUMETIME_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
