
package ido.ConsumeInfo;

/**
 * 关于消费记录的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum ConsumeInfoOrderByFields { 
 SNO,  SNO_DESC , IUSERID,  IUSERID_DESC , COMID,  COMID_DESC , SHOPMID,  SHOPMID_DESC , SHOPID,  SHOPID_DESC , OWNERCOM,  OWNERCOM_DESC , CONSUMESTATUS,  CONSUMESTATUS_DESC , CONSUMEMONEY,  CONSUMEMONEY_DESC , CARDMONEY,  CARDMONEY_DESC , CASHMONEY,  CASHMONEY_DESC , CONSUMETIME,  CONSUMETIME_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
