
package money.question;

public enum QuestionOrderByFields {
	QUESTIONID_DESC,QUESTIONDATE,CONSOLEDATE,SORT,ORDERID,STATUS,
	QUESTIONID,QUESTIONDATE_DESC,CONSOLEDATE_DESC,SORT_DESC,ORDERID_DESC,STATUS_DESC
}