package common.report;

public enum ReportColor {
	//艾利斯兰      
	ALICEBLUE("F0F8FF"),
	//古董白      
	ANTIQUEWHITE("FAEBD7"),
	//浅绿色    
	AQUA("00FFFF"),
	//碧绿色    
	AQUAMARINE("7FFFD4"),
	//天蓝色    
	AZURE("F0FFFF"),
	//米色    
	BEIGE("F5F5DC"),
	//桔黄色      
	BISQUE("FFE4C4"),
	//黑色    
	BLACK("000000"),
	//白杏色    
	BLANCHEDALMOND("FFEBCD"),
	//蓝色      
	BLUE("0000FF"),
	//紫罗兰色    
	BLUEVIOLET("8A2BE2"),
	//褐色    
	BROWN("A52A2A"),
	//实木色    
	BURLYWOOD("DEB887"),
	//军兰色    
	CADETBLUE("5F9EA0"),
	//黄绿色    
	CHARTREUSE("7FFF00"),
	//巧可力色      
	CHOCOLATE("D2691E"),
	//珊瑚色    
	CORAL("FF7F50"),
	//菊兰色    
	CORNFLOWERBLUE("6495ED"),
	//米绸色      
	CORNSILK("FFF8DC"),
	//暗深红色    
	CRIMSON("DC143C"),
	//青色    
	CYAN("00FFFF"),
	//暗蓝色    
	DARKBLUE("00008B"),
	//暗青色    
	DARKCYAN("008B8B"),
	//暗金黄色    
	DARKGOLDENROD("B8860B"),
	//暗灰色    
	DARKGRAY("A9A9A9"),
	//暗绿色    
	DARKGREEN("006400"),
	//暗黄褐色    
	DARKKHAKI("BDB76B"),
	//暗洋红      
	DARKMAGENTA("8B008B"),
	//暗橄榄绿    
	DARKOLIVEGREEN("556B2F"),
	//暗桔黄色    
	DARKORANGE("FF8C00"),
	//暗紫色    
	DARKORCHID("9932CC"),
	//暗红色    
	DARKRED("8B0000"),
	//暗肉色    
	DARKSALMON("E9967A"),
	//暗海兰色    
	DARKSEAGREEN("8FBC8F"),
	//暗灰蓝色    
	DARKSLATEBLUE("483D8B"),
	//墨绿色      
	DARKSLATEGRAY("2F4F4F"),
	//暗宝石绿    
	DARKTURQUOISE("00CED1"),
	//暗紫罗兰色    
	DARKVIOLET("9400D3"),
	//深粉红色    
	DEEPPINK("FF1493"),
	//深天蓝色    
	DEEPSKYBLUE("00BFFF"),
	//暗灰色    
	DIMGRAY("696969"),
	//闪兰色    
	DODGERBLUE("1E90FF"),
	//火砖色    
	FIREBRICK("B22222"),
	//花白色      
	FLORALWHITE("FFFAF0"),
	//森林绿      
	FORESTGREEN("228B22"),
	//紫红色    
	FUCHSIA("FF00FF"),
	//淡灰色    
	GAINSBORO("DCDCDC"),
	//幽灵白    
	GHOSTWHITE("F8F8FF"),
	//金色    
	GOLD("FFD700"),
	//金麒麟色    
	GOLDENROD("DAA520"),
	//灰色    
	GRAY("808080"),
	//绿色    
	GREEN("008000"),
	//黄绿色    
	GREENYELLOW("ADFF2F"),
	//蜜色      
	HONEYDEW("F0FFF0"),
	//热粉红色    
	HOTPINK("FF69B4"),
	//印第安红    
	INDIANRED("CD5C5C"),
	//靛青色    
	INDIGO("4B0082"),
	//象牙色    
	IVORY("FFFFF0"),
	//黄褐色    
	KHAKI("F0E68C"),
	//淡紫色      
	LAVENDER("E6E6FA"),
	//淡紫红    
	LAVENDERBLUSH("FFF0F5"),
	//草绿色    
	LAWNGREEN("7CFC00"),
	//柠檬绸色    
	LEMONCHIFFON("FFFACD"),
	//亮蓝色    
	LIGHTBLUE("ADD8E6"),
	//亮珊瑚色    
	LIGHTCORAL("F08080"),
	//亮青色    
	LIGHTCYAN("E0FFFF"),
	//亮金黄色      
	LIGHTGOLDENRODYELLOW("FAFAD2"),
	//亮绿色      
	LIGHTGREEN("90EE90"),
	//亮灰色    
	LIGHTGREY("D3D3D3"),
	//亮粉红色    
	LIGHTPINK("FFB6C1"),
	//亮肉色    
	LIGHTSALMON("FFA07A"),
	//亮海蓝色    
	LIGHTSEAGREEN("20B2AA"),
	//亮天蓝色    
	LIGHTSKYBLUE("87CEFA"),
	//亮蓝灰    
	LIGHTSLATEGRAY("778899"),
	//亮钢兰色    
	LIGHTSTEELBLUE("B0C4DE"),
	//亮黄色    
	LIGHTYELLOW("FFFFE0"),
	//酸橙色    
	LIME("00FF00"),
	//橙绿以    
	LIMEGREEN("32CD32"),
	//亚麻色    
	LINEN("FAF0E6"),
	//红紫色    
	MAGENTA("FF00FF"),
	//粟色    
	MAROON("800000"),
	//间绿色    
	MEDIUMAQUAMARINE("66CDAA"),
	//间兰色    
	MEDIUMBLUE("0000CD"),
	//间紫色    
	MEDIUMORCHID("BA55D3"),
	//间紫色    
	MEDIUMPURPLE("9370DB"),
	//间海蓝    
	MEDIUMSEAGREEN("3CB371"),
	//间暗蓝色    
	MEDIUMSLATEBLUE("7B68EE"),
	//间春绿色    
	MEDIUMSPRINGGREEN("00FA9A"),
	//间绿宝石    
	MEDIUMTURQUOISE("48D1CC"),
	//间紫罗兰色    
	MEDIUMVIOLETRED("C71585"),
	//中灰兰色    
	MIDNIGHTBLUE("191970"),
	//薄荷色    
	MINTCREAM("F5FFFA"),
	//浅玫瑰色    
	MISTYROSE("FFE4E1"),
	//鹿皮色    
	MOCCASIN("FFE4B5"),
	//纳瓦白    
	NAVAJOWHITE("FFDEAD"),
	//海军色    
	NAVY("000080"),
	//老花色    
	OLDLACE("FDF5E6"),
	//橄榄色    
	OLIVE("808000"),
	//深绿褐色    
	OLIVEDRAB("6B8E23"),
	//橙色    
	ORANGE("FFA500"),
	//红橙色    
	ORANGERED("FF4500"),
	//淡紫色    
	ORCHID("DA70D6"),
	//苍麒麟色    
	PALEGOLDENROD("EEE8AA"),
	//苍绿色      
	PALEGREEN("98FB98"),
	//苍宝石绿      
	PALETURQUOISE("AFEEEE"),
	//苍紫罗兰色    
	PALEVIOLETRED("DB7093"),
	//番木色    
	PAPAYAWHIP("FFEFD5"),
	//桃色    
	PEACHPUFF("FFDAB9"),
	//秘鲁色    
	PERU("CD853F"),
	//粉红色    
	PINK("FFC0CB"),
	//洋李色    
	PLUM("DDA0DD"),
	//粉蓝色    
	POWDERBLUE("B0E0E6"),
	//紫色    
	PURPLE("800080"),
	//红色    
	RED("FF0000"),
	//褐玫瑰红    
	ROSYBROWN("BC8F8F"),
	//皇家蓝    
	ROYALBLUE("4169E1"),
	//重褐色      
	SADDLEBROWN("8B4513"),
	//鲜肉色    
	SALMON("FA8072"),
	//沙褐色    
	SANDYBROWN("F4A460"),
	//海绿色    
	SEAGREEN("2E8B57"),
	//海贝色    
	SEASHELL("FFF5EE"),
	//赭色    
	SIENNA("A0522D"),
	//银色    
	SILVER("C0C0C0"),
	//天蓝色    
	SKYBLUE("87CEEB"),
	//石蓝色    
	SLATEBLUE("6A5ACD"),
	//灰石色    
	SLATEGRAY("708090"),
	//雪白色    
	SNOW("FFFAFA"),
	//春绿色    
	SPRINGGREEN("00FF7F"),
	//钢兰色    
	STEELBLUE("4682B4"),
	//茶色    
	TAN("D2B48C"),
	//水鸭色    
	TEAL("008080"),
	//蓟色    
	THISTLE("D8BFD8"),
	//西红柿色    
	TOMATO("FF6347"),
	//青绿色    
	TURQUOISE("40E0D0"),
	//紫罗兰色    
	VIOLET("EE82EE"),
	//浅黄色    
	WHEAT("F5DEB3"),
	//白色    
	WHITE("FFFFFF"),
	//烟白色    
	WHITESMOKE("F5F5F5"),
	//黄色    
	YELLOW("FFFF00"),
	//黄绿色 
	YELLOWGREEN("9ACD32");  
	private String color;
	ReportColor(String color){
		this.color = color;
	}
	public String getColor(){
		return this.color;
	} 
}
