
package ido.loginfo;

/**
 * 关于操作日志的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum LogInfoSearchFields { 
 SNO , OPERUSER , OPERUSERNAME , OPERTIME , OPERTYPE , OPERIP , OPERURL , OPERBEFORE , OPERAFTER , OPERDESC ,OPERUSER_COM_EQUALS,OPERUSER_COM_NOT_EQUALS
,OPERUSERNAME_COM_EQUALS,OPERUSERNAME_COM_NOT_EQUALS
,OPERTIME_COM_EQUALS,OPERTIME_COM_NOT_EQUALS
,OPERTYPE_COM_EQUALS,OPERTYPE_COM_NOT_EQUALS
,OPERIP_COM_EQUALS,OPERIP_COM_NOT_EQUALS
,OPERURL_COM_EQUALS,OPERURL_COM_NOT_EQUALS
,OPERBEFORE_COM_EQUALS,OPERBEFORE_COM_NOT_EQUALS
,OPERAFTER_COM_EQUALS,OPERAFTER_COM_NOT_EQUALS
,OPERDESC_COM_EQUALS,OPERDESC_COM_NOT_EQUALS
}
