
package ido.InsuredCompany;

/**
 * 关于保险公司的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum InsuredCompanySearchFields { 
 SNO , COMNAME , COMNO , COMSTATUS , COMSHORTNAME , COMPHONE , COMCONTACTNAME , COMCONTACTPHONE , OWNERCOMPANY , COMEMAIL , COMADDRESS , COMREMARK , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,COMNAME_STR_EQUALS,COMNAME_STR_LIKE,COMNAME_STR_NOT_LIKE,COMNAME_STR_NOT_EQUALS
,COMNO_STR_EQUALS,COMNO_STR_LIKE,COMNO_STR_NOT_LIKE,COMNO_STR_NOT_EQUALS
,COMSTATUS_COM_EQUALS,COMSTATUS_COM_NOT_EQUALS
,COMSHORTNAME_STR_EQUALS,COMSHORTNAME_STR_LIKE,COMSHORTNAME_STR_NOT_LIKE,COMSHORTNAME_STR_NOT_EQUALS
,COMPHONE_STR_EQUALS,COMPHONE_STR_LIKE,COMPHONE_STR_NOT_LIKE,COMPHONE_STR_NOT_EQUALS
,COMCONTACTNAME_STR_EQUALS,COMCONTACTNAME_STR_LIKE,COMCONTACTNAME_STR_NOT_LIKE,COMCONTACTNAME_STR_NOT_EQUALS
,COMCONTACTPHONE_STR_EQUALS,COMCONTACTPHONE_STR_LIKE,COMCONTACTPHONE_STR_NOT_LIKE,COMCONTACTPHONE_STR_NOT_EQUALS
,OWNERCOMPANY_COM_EQUALS,OWNERCOMPANY_COM_NOT_EQUALS
,COMEMAIL_STR_EQUALS,COMEMAIL_STR_LIKE,COMEMAIL_STR_NOT_LIKE,COMEMAIL_STR_NOT_EQUALS
,COMADDRESS_STR_EQUALS,COMADDRESS_STR_LIKE,COMADDRESS_STR_NOT_LIKE,COMADDRESS_STR_NOT_EQUALS
,COMREMARK_STR_EQUALS,COMREMARK_STR_LIKE,COMREMARK_STR_NOT_LIKE,COMREMARK_STR_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_DATE_EQUALS,CREATETIME_DATE_NOT_LATTER,CREATETIME_DATE_NOT_EARLY,CREATETIME_DATE_LATTER,CREATETIME_DATE_EARLY
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_DATE_EQUALS,UPDATETIME_DATE_NOT_LATTER,UPDATETIME_DATE_NOT_EARLY,UPDATETIME_DATE_LATTER,UPDATETIME_DATE_EARLY
}
