
package ido.InsuredCompany;

/**
 * 关于保险公司的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum InsuredCompanyOrderByFields { 
 SNO,  SNO_DESC , COMNAME,  COMNAME_DESC , COMNO,  COMNO_DESC , COMSTATUS,  COMSTATUS_DESC , COMSHORTNAME,  COMSHORTNAME_DESC , COMPHONE,  COMPHONE_DESC , COMCONTACTNAME,  COMCONTACTNAME_DESC , COMCONTACTPHONE,  COMCONTACTPHONE_DESC , OWNERCOMPANY,  OWNERCOMPANY_DESC , COMEMAIL,  COMEMAIL_DESC , COMADDRESS,  COMADDRESS_DESC , COMREMARK,  COMREMARK_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
