
package ido.Dict_Drugtype;

/**
 * 关于药品大类字典表的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum DrugTypeSelectSearchFields { 
 SNO , DRUGTYPE , TYPESTATUS , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,DRUGTYPE_COM_EQUALS,DRUGTYPE_COM_NOT_EQUALS
,TYPESTATUS_COM_EQUALS,TYPESTATUS_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
