package money.menu;

public enum MenuOrderByFields {
	MENUID, MENUID_DESC, MENUNAME, MENUNAME_DESC, 
	URL, URL_DESC, TARGET, TARGET_DESC, PARENTID, 
	PARENTID_DESC, LEVEL, LEVEL_DESC, ORDERID, 
	ORDERID_DESC, RELID, RELID_DESC
}
