
package money.addRole2;

/**
 * 关于新角色授权的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum AddRoleSearchFields { 
 SNO , ROLETYPE , ROLEKEY , ROLEIDS , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,ROLETYPE_COM_EQUALS,ROLETYPE_COM_NOT_EQUALS
,ROLEKEY_COM_EQUALS,ROLEKEY_COM_NOT_EQUALS
,ROLEIDS_COM_EQUALS,ROLEIDS_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
