
package ido.InsuredFile;

/**
 * 关于投保单的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum InsuredFileOrderByFields { 
 SNO,  SNO_DESC , INSUREDFILEID,  INSUREDFILEID_DESC , INSUREDFILENAME,  INSUREDFILENAME_DESC , INSUREDFILEUNIT,  INSUREDFILEUNIT_DESC , INSUREDFILECOMPANY,  INSUREDFILECOMPANY_DESC , INSUREDFILEEMAIL,  INSUREDFILEEMAIL_DESC , INSUREDFILECONTACT,  INSUREDFILECONTACT_DESC , INSUREDFILECONTEL,  INSUREDFILECONTEL_DESC , INSUREDFILECONMOBILE,  INSUREDFILECONMOBILE_DESC , INSUREDFILEBEGIN,  INSUREDFILEBEGIN_DESC , INSUREDFILEEND,  INSUREDFILEEND_DESC , INSUREDFILESTATUS,  INSUREDFILESTATUS_DESC , INSUREDFILEDUIJIE,  INSUREDFILEDUIJIE_DESC , INSUREDFILEDUIJIEFLAG,  INSUREDFILEDUIJIEFLAG_DESC , INSUREDFILEREMARK,  INSUREDFILEREMARK_DESC , INSUREDFILETOTAL,  INSUREDFILETOTAL_DESC , INSUREDFILEEMERG,  INSUREDFILEEMERG_DESC , INSUREDFILEHOSPITAL,  INSUREDFILEHOSPITAL_DESC , INSUREDFILEEXAM,  INSUREDFILEEXAM_DESC , INSUREDFILECONSUMER,  INSUREDFILECONSUMER_DESC , INSUREDFILECONSRULE,  INSUREDFILECONSRULE_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
