
package ido.BusinessMan;

/**
 * 关于商家的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum BusinessManOrderByFields { 
 SNO,  SNO_DESC , SHOPMSNO,  SHOPMSNO_DESC , SHOPMNAME,  SHOPMNAME_DESC , SHOPMSHORTNAME,  SHOPMSHORTNAME_DESC , SHOPMTYPE,  SHOPMTYPE_DESC , SHOPMEMAIL,  SHOPMEMAIL_DESC , SHOPMCONPHONE,  SHOPMCONPHONE_DESC , SHOPMCONTACTNAME,  SHOPMCONTACTNAME_DESC , SHOPMADDRESS,  SHOPMADDRESS_DESC , OPENBANK,  OPENBANK_DESC , OPENBANKNAME,  OPENBANKNAME_DESC , OPENBANKNO,  OPENBANKNO_DESC , OPENTICKETUNIT,  OPENTICKETUNIT_DESC , OPENBANKPROVINCE,  OPENBANKPROVINCE_DESC , OPENBANKCITY,  OPENBANKCITY_DESC , COMPENSATIONDAY,  COMPENSATIONDAY_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
