
package ido.BusinessMan;

/**
 * 关于商家的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum BusinessManSearchFields { 
 SNO , SHOPMSNO , SHOPMNAME ,GROUPSNO, SHOPMSHORTNAME , SHOPMTYPE , SHOPMEMAIL , SHOPMCONPHONE , SHOPMCONTACTNAME , SHOPMADDRESS , OPENBANK , OPENBANKNAME , OPENBANKNO , OPENTICKETUNIT , OPENBANKPROVINCE , OPENBANKCITY , COMPENSATIONDAY , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,SHOPMSNO_COM_EQUALS,SHOPMSNO_COM_NOT_EQUALS
,SHOPMNAME_COM_EQUALS,SHOPMNAME_COM_NOT_EQUALS
,SHOPMSHORTNAME_COM_EQUALS,SHOPMSHORTNAME_COM_NOT_EQUALS
,SHOPMTYPE_COM_EQUALS,SHOPMTYPE_COM_NOT_EQUALS
,SHOPMEMAIL_COM_EQUALS,SHOPMEMAIL_COM_NOT_EQUALS
,SHOPMCONPHONE_COM_EQUALS,SHOPMCONPHONE_COM_NOT_EQUALS
,SHOPMCONTACTNAME_COM_EQUALS,SHOPMCONTACTNAME_COM_NOT_EQUALS
,SHOPMADDRESS_COM_EQUALS,SHOPMADDRESS_COM_NOT_EQUALS
,OPENBANK_COM_EQUALS,OPENBANK_COM_NOT_EQUALS
,OPENBANKNAME_COM_EQUALS,OPENBANKNAME_COM_NOT_EQUALS
,OPENBANKNO_COM_EQUALS,OPENBANKNO_COM_NOT_EQUALS
,OPENTICKETUNIT_COM_EQUALS,OPENTICKETUNIT_COM_NOT_EQUALS
,OPENBANKPROVINCE_COM_EQUALS,OPENBANKPROVINCE_COM_NOT_EQUALS
,OPENBANKCITY_COM_EQUALS,OPENBANKCITY_COM_NOT_EQUALS
,COMPENSATIONDAY_COM_EQUALS,COMPENSATIONDAY_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
