package dwz.persistence.beans;

import java.util.Date;

/**
 * InfNews generated by MyEclipse Persistence Tools
 */

public class InfNews implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 7044485641608038943L;
	private Integer id;
	private String type;
	private Integer companyId;
	private String status;
	private String title;
	private String content;
	private String author;
	private String source;
	private Date insertDate;
	private Date updateDate;

	// Constructors

	/** default constructor */
	public InfNews() {
	}

	/** minimal constructor */
	public InfNews(String type, String status,
			Date insertDate, Date updateDate) {
		this.type = type;
		this.status = status;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
	}

	/** full constructor */
	public InfNews(Integer companyId, String type, String status, String title,
			String content, String author, String source, Date insertDate,
			Date updateDate) {
		this.companyId = companyId;
		this.type = type;
		this.status = status;
		this.title = title;
		this.content = content;
		this.author = author;
		this.source = source;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}