package dwz.persistence.beans;

// Generated 2011-5-24 15:43:26 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * InvCategory generated by hbm2java
 */
public class InvCategory implements java.io.Serializable {

	private Integer id;
	private Integer pid;
	private Integer lft;
	private Integer rgt;
	private String name;
	private String description;
	private String metaTitle;
	private String metaKeyword;
	private String metaDescription;
	private String picUrl;
	private int productNum;
	private Date insertDate;
	private Date updateDate;

	public InvCategory() {
	}

	public InvCategory(int productNum, Date insertDate, Date updateDate) {
		this.productNum = productNum;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
	}

	public InvCategory(Integer pid, Integer lft, Integer rgt, String name,
			String description, String metaTitle, String metaKeyword,
			String metaDescription, String picUrl, int productNum,
			Date insertDate, Date updateDate) {
		this.pid = pid;
		this.lft = lft;
		this.rgt = rgt;
		this.name = name;
		this.description = description;
		this.metaTitle = metaTitle;
		this.metaKeyword = metaKeyword;
		this.metaDescription = metaDescription;
		this.picUrl = picUrl;
		this.productNum = productNum;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Integer getLft() {
		return this.lft;
	}

	public void setLft(Integer lft) {
		this.lft = lft;
	}

	public Integer getRgt() {
		return this.rgt;
	}

	public void setRgt(Integer rgt) {
		this.rgt = rgt;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMetaTitle() {
		return this.metaTitle;
	}

	public void setMetaTitle(String metaTitle) {
		this.metaTitle = metaTitle;
	}

	public String getMetaKeyword() {
		return this.metaKeyword;
	}

	public void setMetaKeyword(String metaKeyword) {
		this.metaKeyword = metaKeyword;
	}

	public String getMetaDescription() {
		return this.metaDescription;
	}

	public void setMetaDescription(String metaDescription) {
		this.metaDescription = metaDescription;
	}

	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	public int getProductNum() {
		return this.productNum;
	}

	public void setProductNum(int productNum) {
		this.productNum = productNum;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
