package dwz.persistence.beans;

import java.util.Date;

/**
 * SetPreference generated by MyEclipse Persistence Tools
 */

public class SetPreference implements java.io.Serializable {

	// Fields

	private Integer id;
	private Integer companyId;
	private String refKey;
	private String refValue;
	private Date insertDate;
	private Date updateDate;

	// Constructors

	/** default constructor */
	public SetPreference() {
	}

	/** minimal constructor */
	public SetPreference(Integer companyId, String refKey, Date insertDate) {
		this.companyId = companyId;
		this.refKey = refKey;
		this.insertDate = insertDate;
	}

	/** full constructor */
	public SetPreference(Integer companyId, String refKey, String refValue,
			Date insertDate, Date updateDate) {
		this.companyId = companyId;
		this.refKey = refKey;
		this.refValue = refValue;
		this.insertDate = insertDate;
		this.updateDate = updateDate;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}

	public String getRefKey() {
		return this.refKey;
	}

	public void setRefKey(String refKey) {
		this.refKey = refKey;
	}

	public String getRefValue() {
		return this.refValue;
	}

	public void setRefValue(String refValue) {
		this.refValue = refValue;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}