package dwz.persistence.beans;

import java.util.Date;

/**
 * SysLog generated by MyEclipse Persistence Tools
 */

public class SysLog implements java.io.Serializable {

	private static final long	serialVersionUID	= 5338354111306002270L;
	private String	id;
	private String	userId;
	private String	logType;
	private String	logLevel;
	private String	ipAddress;
	private String	name;
	private String	content;
	private Date	insertDate;

	// Constructors

	/** default constructor */
	public SysLog() {
	}

	/** minimal constructor */
	public SysLog(String userId, String logType, String logLevel,
			Date insertDate) {
		this.userId = userId;
		this.logType = logType;
		this.logLevel = logLevel;
		this.insertDate = insertDate;
	}

	/** full constructor */
	public SysLog(String userId, String logType, String logLevel,
			String ipAddress, String name, String content, Date insertDate) {
		this.userId = userId;
		this.logType = logType;
		this.logLevel = logLevel;
		this.ipAddress = ipAddress;
		this.name = name;
		this.content = content;
		this.insertDate = insertDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	public String getLogLevel() {
		return this.logLevel;
	}

	public void setLogLevel(String logLevel) {
		this.logLevel = logLevel;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

}