package dwz.persistence.beans;

import java.util.HashSet;
import java.util.Set;

/**
 * SysRole generated by MyEclipse Persistence Tools
 */

public class SysRole implements java.io.Serializable {

	// Fields

	private Integer id;
	private String name;
	private String description;
	private String status;

	private Set sysPermissions = new HashSet(0);
	private Set sysUserRoles = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysRole() {
	}

	/** minimal constructor */
	public SysRole(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	/** full constructor */
	public SysRole(Integer id, String description, String name, String status,
			Set sysPermissions, Set sysUserRoles) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.status = status;
		this.sysPermissions = sysPermissions;
		this.sysUserRoles = sysUserRoles;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getSysPermissions() {
		return this.sysPermissions;
	}

	public void setSysPermissions(Set sysPermissions) {
		this.sysPermissions = sysPermissions;
	}

	public Set getSysUserRoles() {
		return this.sysUserRoles;
	}

	public void setSysUserRoles(Set sysUserRoles) {
		this.sysUserRoles = sysUserRoles;
	}

}