package dwz.persistence.beans;

import java.util.HashSet;
import java.util.Set;

/**
 * SysResource generated by MyEclipse Persistence Tools
 */

public class SysResource implements java.io.Serializable {

	// Fields

	private Integer id;
	private String sn;
	private String name;
	private String description;
	private Short purview;
	private Set sysPermissions = new HashSet(0);

	// Constructors

	/** default constructor */
	public SysResource() {
	}

	/** minimal constructor */
	public SysResource(Integer id, String sn, Short purview) {
		this.id = id;
		this.sn = sn;
		this.purview = purview;
	}

	/** full constructor */
	public SysResource(Integer id, String sn, String name, String description,
			Short purview, Set sysPermissions) {
		this.id = id;
		this.sn = sn;
		this.name = name;
		this.description = description;
		this.purview = purview;
		this.sysPermissions = sysPermissions;
	}

	// Property accessors

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSn() {
		return this.sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Short getPurview() {
		return this.purview;
	}

	public void setPurview(Short purview) {
		this.purview = purview;
	}

	public Set getSysPermissions() {
		return this.sysPermissions;
	}

	public void setSysPermissions(Set sysPermissions) {
		this.sysPermissions = sysPermissions;
	}

}