package dwz.persistence.beans;

import java.util.Date;

/**
 * AbstractSysSession generated by MyEclipse Persistence Tools
 */

public class SysSession implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6469915526934532126L;
	private String id;
	private String userId;
	private String sessionIp;
	private Date startDate;
	private Date accessDate;

	// Constructors

	/** default constructor */
	public SysSession() {
	}

	public String getSessionIp() {
		return sessionIp;
	}

	public void setSessionIp(String sessionIp) {
		this.sessionIp = sessionIp;
	}

	/** full constructor */
	public SysSession(String id, String userId, String sessionIp,
			Date startDate, Date accessDate) {
		this.id = id;
		this.userId = userId;
		this.sessionIp = sessionIp;
		this.startDate = startDate;

		this.accessDate = accessDate;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getAccessDate() {
		return this.accessDate;
	}

	public void setAccessDate(Date accessDate) {
		this.accessDate = accessDate;
	}

}