
package ido.bindFamily;

/**
 * 关于投保用户的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum BindFamilySearchFields { 
 SNO , IUSERNO , BINDNAME , RELATION , CARDNO , PHONE , CREATEUSER , CREATETIME ,IUSERNO_COM_EQUALS,IUSERNO_COM_NOT_EQUALS
,BINDNAME_COM_EQUALS,BINDNAME_COM_NOT_EQUALS
,RELATION_COM_EQUALS,RELATION_COM_NOT_EQUALS
,CARDNO_COM_EQUALS,CARDNO_COM_NOT_EQUALS
,PHONE_COM_EQUALS,PHONE_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
}
