
package ido.InsuredUser;

/**
 * 关于投保用户的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum InsuredUserOrderByFields { 
 SNO,  SNO_DESC , IUSERNO,  IUSERNO_DESC , COMID,  COMID_DESC , UNITID,  UNITID_DESC , IUSERSTATUS,  IUSERSTATUS_DESC , IUSERNUMBER,  IUSERNUMBER_DESC , LEFTMONEY,  LEFTMONEY_DESC , EMERGENCYMONEY,  EMERGENCYMONEY_DESC , FROZENMONEY,  FROZENMONEY_DESC , HOSPITALMONEY,  HOSPITALMONEY_DESC , TESMONEY,  TESMONEY_DESC , IUSERNAME,  IUSERNAME_DESC , IUSERISMAN,  IUSERISMAN_DESC , IUSERCARDNO,  IUSERCARDNO_DESC , IUSERPHONE,  IUSERPHONE_DESC , IUSEREMAIL,  IUSEREMAIL_DESC , IUSERBIRTHDAY,  IUSERBIRTHDAY_DESC , IUSERREMARK,  IUSERREMARK_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
