
package ido.InsuredUser;

/**
 * 关于投保用户的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum InsuredUserSearchFields { 
 SNO , IUSERNO , COMID , UNITID , IUSERSTATUS , IUSERNUMBER , LEFTMONEY , EMERGENCYMONEY , FROZENMONEY , HOSPITALMONEY , TESMONEY , IUSERNAME , IUSERISMAN , IUSERCARDNO , IUSERPHONE , IUSEREMAIL , IUSERBIRTHDAY , IUSERREMARK , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,IUSERNO_COM_EQUALS,IUSERNO_COM_NOT_EQUALS
,COMID_COM_EQUALS,COMID_COM_NOT_EQUALS
,UNITID_COM_EQUALS,UNITID_COM_NOT_EQUALS
,IUSERSTATUS_COM_EQUALS,IUSERSTATUS_COM_NOT_EQUALS
,IUSERNUMBER_COM_EQUALS,IUSERNUMBER_COM_NOT_EQUALS
,LEFTMONEY_COM_EQUALS,LEFTMONEY_COM_NOT_EQUALS
,EMERGENCYMONEY_COM_EQUALS,EMERGENCYMONEY_COM_NOT_EQUALS
,FROZENMONEY_COM_EQUALS,FROZENMONEY_COM_NOT_EQUALS
,HOSPITALMONEY_COM_EQUALS,HOSPITALMONEY_COM_NOT_EQUALS
,TESMONEY_COM_EQUALS,TESMONEY_COM_NOT_EQUALS
,IUSERNAME_COM_EQUALS,IUSERNAME_COM_NOT_EQUALS
,IUSERISMAN_COM_EQUALS,IUSERISMAN_COM_NOT_EQUALS
,IUSERCARDNO_COM_EQUALS,IUSERCARDNO_COM_NOT_EQUALS
,IUSERPHONE_COM_EQUALS,IUSERPHONE_COM_NOT_EQUALS
,IUSEREMAIL_COM_EQUALS,IUSEREMAIL_COM_NOT_EQUALS
,IUSERBIRTHDAY_COM_EQUALS,IUSERBIRTHDAY_COM_NOT_EQUALS
,IUSERREMARK_COM_EQUALS,IUSERREMARK_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
