
package ido.addmoneydetail;

/**
 * 关于充值记录明细的查询枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum AddMoneyDetailSearchFields { 
 SNO , IUSERID , ADDTYPE , ADDMONEY , INSUREDFILEID , ADDTIME , CREATEUSER , CREATETIME , UPDATEUSER , UPDATETIME ,IUSERID_COM_EQUALS,IUSERID_COM_NOT_EQUALS
,ADDTYPE_COM_EQUALS,ADDTYPE_COM_NOT_EQUALS
,ADDMONEY_COM_EQUALS,ADDMONEY_COM_NOT_EQUALS
,INSUREDFILEID_COM_EQUALS,INSUREDFILEID_COM_NOT_EQUALS
,ADDTIME_COM_EQUALS,ADDTIME_COM_NOT_EQUALS
,CREATEUSER_COM_EQUALS,CREATEUSER_COM_NOT_EQUALS
,CREATETIME_COM_EQUALS,CREATETIME_COM_NOT_EQUALS
,UPDATEUSER_COM_EQUALS,UPDATEUSER_COM_NOT_EQUALS
,UPDATETIME_COM_EQUALS,UPDATETIME_COM_NOT_EQUALS
}
