
package ido.InsuredUnit;

/**
 * 关于投保单位的查询排序枚举类.
 * @author www(水清)
 * 任何人和公司可以传播并且修改本程序，但是不得去掉本段声明以及作者署名.
 * http://www.iteye.com
 */
public enum InsuredUnitOrderByFields { 
 SNO,  SNO_DESC , UNITCODE,  UNITCODE_DESC , UNITNAME,  UNITNAME_DESC , CONTACTNAME,  CONTACTNAME_DESC , CONTACTMOBILE,  CONTACTMOBILE_DESC , CONTACTEMAIL,  CONTACTEMAIL_DESC , UNITPARENTID,  UNITPARENTID_DESC , UNITSTATE,  UNITSTATE_DESC , UNITADDRESS,  UNITADDRESS_DESC , UNITREMARK,  UNITREMARK_DESC , CREATEUSER,  CREATEUSER_DESC , CREATETIME,  CREATETIME_DESC , UPDATEUSER,  UPDATEUSER_DESC , UPDATETIME,  UPDATETIME_DESC 
}
